brew "aria2"
brew "khell/srm/srm"
brew "openvpn"
brew "zsh"

cask "aerial"
cask "alfred"
cask "bitbar"
cask "canary"
cask "castbridge"
cask "google-chrome"
cask "iterm2"
cask "keka"
cask "macpass"
cask "nordvpn"
cask "osxfuse"
cask "skype"
cask "spotify"
cask "veracrypt"
cask "vlc"
cask "whatsapp"

tap "homebrew/cask-drivers"
cask "homebrew/cask-drivers/synology-drive"

tap "homebrew/cask-fonts"
cask "homebrew/cask-fonts/font-hack-nerd-font"
